#!/bin/tcsh -f

# OVERCLOCKING
# experimental GPU overclocking
#/usr/bin/nvidia-settings -a '[gpu:0]/GPUGraphicsClockOffset[3]=100'
#/usr/bin/nvidia-settings -a '[gpu:1]/GPUGraphicsClockOffset[3]=100'
#/usr/bin/nvidia-settings -a '[gpu:2]/GPUGraphicsClockOffset[3]=100'
#/usr/bin/nvidia-settings -a '[gpu:3]/GPUGraphicsClockOffset[3]=100'
# experimental MEM overclocking
/usr/bin/nvidia-settings -a '[gpu:0]/GPUMemoryTransferRateOffset[3]=750'
/usr/bin/nvidia-settings -a '[gpu:1]/GPUMemoryTransferRateOffset[3]=750'
/usr/bin/nvidia-settings -a '[gpu:2]/GPUMemoryTransferRateOffset[3]=750'
/usr/bin/nvidia-settings -a '[gpu:3]/GPUMemoryTransferRateOffset[3]=750'

#set test=(`/usr/bin/nvidia-smi dmon -i 0 -s p -c 1 | sort -n -k3 | tail -1`)
set count=(`/usr/bin/nvidia-smi -i 0 --query-gpu=count --format=csv,noheader`)
#`/usr/bin/nvidia-xconfig --allow-empty-initial-configuration --cool-bits=28 --enable-all-gpus`
#/usr/bin/nvidia-smi -pm 1

@ cardIteratorMax = $count
@ cardIterator = 0
@ target = 40

while (1)
	while ($cardIterator < $cardIteratorMax)
	 # TEST TEMP and SET FAN SPEED
	 @ temp = `/usr/bin/nvidia-smi -i $cardIterator --format=csv,noheader --query-gpu=temperature.gpu`
	 if (${temp} <= 40) then
	  @ target = 40
	 endif
	 if (${temp} > 40 && ${temp} <= 45) then
	  @ target = 45
	 endif
	 if (${temp} > 45 && ${temp} <= 55) then
	  @ target = 50
	 endif
	 if (${temp} > 55 && ${temp} <= 60) then
	  @ target = 55
	 endif
         if (${temp} > 60 && ${temp} <= 65) then
          @ target = 60
         endif
	 if (${temp} > 65 && ${temp} <= 70) then
	  @ target = 65
	 endif
	 if (${temp} > 70 && ${temp} <= 75) then
	  @ target = 70
	 endif
	 if (${temp} > 75) then
	  @ target = 75
	 endif
	
	 echo "Current temperature is ${temp}.  Setting fan speed to ${target}."

	 /usr/bin/nvidia-settings -a '[gpu:'${cardIterator}']/GPUFanControlState=1' -a '[fan:'${cardIterator}']/GPUTargetFanSpeed='${target}

	 @ cardIterator += 1
	end

@ cardIterator = 0
sleep 5
end
